name: evalutia
services:
  mysql:
    image: mysql:8.0
    container_name: evalutia-mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      TZ: ${TZ}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./infra/sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping -h 127.0.0.1 -u "$$MYSQL_USER" -p"$$MYSQL_PASS" || exit 1']
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - evalutia_net
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: evalutia-adminer
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      TZ: ${TZ}
    ports:
      - "8080:8080"
    networks:
      - evalutia_net
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: evalutia-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - evalutia_net
    restart: unless-stopped

networks:
  evalutia_net:

volumes:
  mysql_data:
